---
title: "ASML Regression R Code Part 1"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
data(Orange)
plot(Orange$age, Orange$circumference)
```


```{r}
fit.ls <- lm(circumference~age, data=Orange)
fit.ls
plot(Orange$age, Orange$circumference)
abline(fit.ls, col=2, lwd=2)
```

```{r}
s <- summary(fit.ls)$sigma
s^2
summary(fit.ls)

```


```{r}
require(quantreg)
fit.rq <- rq(circumference~age, data=Orange)
fit.rq
plot(Orange$age, Orange$circumference)
abline(fit.ls, col=2, lwd=2)
abline(fit.rq, col=3, lwd=2) 
legend(100,200, c("L2", "L1"), col=c(2,3), lwd=c(2,2))
```

```{r}
n     <- 1000
beta0 <- -1;    beta1 <- 2
sigma <- sqrt(2)
x     <- runif(1000, -5,5)  
y     <-  rnorm(n, beta0+beta1*x, sigma )
plot(x,y)

model1_string <- "model{
  for(i in 1:N){ 
    y[i] ~ dnorm(mu[i], tau)   # tau = precision=inverse variance
    mu[i] <- beta0+beta1*x[i]
  } 
  # Prior distribution on mean
    beta0 ~ dnorm(0, 0.0001);    beta1 ~ dnorm(0, 0.0001)
    tau  ~ dgamma(0.01, 0.01)
    sigma<- 1/sqrt(tau)
}"

require(rjags)
model2 <- jags.model(textConnection(model1_string), data = list(x=x, y=y,N=n))

update(model2, 10000)

postmod2.samples = coda.samples(model2, c("beta0", "beta1", "sigma"), 10000)[[1]]

summary(postmod2.samples)
plot(postmod2.samples )

colMeans(postmod2.samples)

effectiveSize(postmod2.samples) 

```

```{r}
ocean <- read.table(
    "http://www.maths.dur.ac.uk/~dma0je/Data/ocean.dat", 
    header=TRUE, sep=","
    )
head(ocean)
dim(ocean)
pairs(ocean)

```

```{r}
par(mfrow=c(2,2), mai=c(0.3,0.3,0.3,0.3))
for (j in 1:4){
  hist(ocean[,j],  main=colnames(ocean)[j], xlab="")
}
```

```{r}
fit <- lm(Temp ~ Depth + Sal + O2, data=ocean)
fit
summary(fit)

```

```{r}
x1 <- runif(100,0,1)
x2 <- runif(100,0,1)
f <-  1 + 2*x1- 3*x2 

# Define empty vectors
b0hat <- rep(0,500)
b1hat <- rep(0,500)
b2hat <- rep(0,500)

# Simulation
for (j in 1:500){
  y<- f + rnorm(100, 0, 0.1)
  sfit <- lm(y~x1+x2)
  b0hat[j] <- sfit$coef[1]
  b1hat[j] <- sfit$coef[2]
  b2hat[j] <- sfit$coef[3]
}
hat     <- cbind(b0hat, b1hat, b2hat)
colMeans(hat)
pairs(hat)
```

```{r}
confint(fit, level=0.95)
```

```{r}
x0 <- c(250, 34, 1)
c(1,x0) %*% fit$coef
predict(fit, newdata=data.frame(Depth=250, Sal=34, O2=1))
predict(fit, newdata=data.frame(Depth=250, Sal=34, O2=1 ),
interval="prediction", level=0.95)
```

```{r}
par(mfrow=c(1,2), cex=0.6)
plot(fit$residuals)
plot(fit$fitted, fit$residuals) 


```

```{r}
require(MASS)
boxcox(fit)
```

```{r}
lfit <- lm(Temp^(-1) ~ Depth + Sal + O2, data=ocean)
lfit$coef
par(mfrow=c(1,2), cex=0.6)
plot(lfit$residuals)
plot(lfit$fitted, lfit$residuals)
```

```{r}
1/(predict(lfit, newdata=data.frame(Depth=250, Sal=34, O2=1),
  interval="prediction", level=0.95))
```



```{r}
require(LearnBayes)
X=cbind(1,ocean$Depth, ocean$Sal, ocean$O2)
head(X)
bayes.fit <- blinreg(ocean$Temp,X,1000) 
         # uses flat prior for beta

par(mfrow=c(2,2), cex=0.5)
hist(bayes.fit$beta[,2])
hist(bayes.fit$beta[,3])
hist(bayes.fit$beta[,4])
hist(bayes.fit$sigma)

round(colMeans(bayes.fit$beta), digits=2)
round(fit$coef, digits=2) # Least squares
```

```{r}
mean(bayes.fit$sigma)
summary(fit)$sigma # Least squares
```


```{r}
quantile(bayes.fit$beta[,1], probs=c(0.025, 0.975))
quantile(bayes.fit$beta[,2], probs=c(0.025, 0.975))
quantile(bayes.fit$beta[,3], probs=c(0.025, 0.975))
quantile(bayes.fit$beta[,4], probs=c(0.025, 0.975))
```

```{r}
XX <- ocean[,2:4] 
x0 <- c(250, 34,1)
XS <- apply(
  rbind(XX, x0),
      2, scale)
```

```{r}
require(rjags)
model2_string <- "model{
 # Likelihood
  for(i in 1:N){  
    Y[i]   ~ dnorm(mu[i],inv.var)
    mu[i] <- alpha+inprod(X[i,],beta[])
  }
  
  # Values to predict 
  Y0  ~ dnorm(mu0,inv.var)
  mu0 <- alpha+inprod(X[N+1,],beta[])

  # Priors
  for(j in 1:p){
    beta[j] ~ dnorm(0,0.0001)
  }
  alpha     ~ dnorm(0, 0.01)
  inv.var   ~ dgamma(0.01, 0.01)
  sigma     <- 1/sqrt(inv.var)
}"
```


```{r}
model2 <- jags.model(
   textConnection(model2_string), 
   data = list(X=XS, Y=ocean$Temp,N=dim(XX)[1], p=dim(XX)[2])
 )
update(model2,10000)
postmod2.samples = coda.samples(
   model2, 
   c("alpha", "beta", "sigma", "Y0", "mu0"), 
   10000
 )[[1]]

# plot(postmod2.samples, cex=0.5)
```

```{r}
summary(postmod2.samples)
```












