---
title: "ASML Regression R Code Part 2"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
ocean <- read.table(
    "http://www.maths.dur.ac.uk/~dma0je/Data/ocean.dat", 
    header=TRUE, sep=","
    )
```

```{r}
require(glmnet)  
fit.ridge<- glmnet(as.matrix(ocean[,2:4]),
   ocean[,1], family="gaussian", alpha=0)

par(mfrow=c(2,2),  mai=c(0.3,0.3,0.3,0.3))
for (j in 1:4){
plot(fit.ridge$lambda, coef(fit.ridge)[j,], 
       type="l", col=j, lwd=2, cex=2, 
       cex.axis=1, xlab="", ylab="")
}
coef(fit.ridge)
```

```{r}
fit<- lm(Temp~Depth+Sal+O2, data=ocean)
round(fit$coef, digits=4) 
```

```{r}
gaia <- read.table(
    "http://www.maths.dur.ac.uk/~dma0je/Data/gaia.dat", 
    header=TRUE
    )
require(lattice)
s <- sample(nrow(gaia),200)
splom(gaia[s,4:20], cex=0.3, 
      pscales=0)
```

```{r}
set.seed(2)
gaiaX = as.matrix(gaia[,5:20])
gaia.fit.temp=  glmnet(gaiaX, 
   gaia$temp, alpha=1 )
plot(gaia.fit.temp,  xvar="lambda",
   cex.axis=2, cex.lab=1.1, 
   cex=1.1)
```

```{r}
gaia.cv.temp = cv.glmnet(gaiaX, 
   gaia$temp, alpha=1 )
plot(gaia.cv.temp)
lambda <- gaia.cv.temp$lambda.min
log(lambda)
```

```{r}
lambda1 <- gaia.cv.temp$lambda.1se
log(lambda1)

cbind(   coef(gaia.cv.temp, s="lambda.min"),
         coef(gaia.cv.temp, s="lambda.1se")   )
```

```{r}
summary(lm(temperature ~ band2 + band6 + band7+band12, data=gaia))
```

```{r}
require(monomvn)
gaia.blas <- blasso(gaiaX, gaia$temperature)
gaia.blas
plot(gaia.blas, burnin=200)
```


```{r}
gaia.fitlasso<-coef(gaia.cv.temp, s="lambda.min" )
gaia.refit<- lm(temperature~ band1+band2+ band6+band7+band8+band9 +
                band10+band11 + band14+ band15 +band16, data=gaia)
bmean <- apply(gaia.blas$beta, 2,mean)
barplot(rbind(gaia.fitlasso[2:17,1],
  c(gaia.refit$coef[2:3],rep(0,3), 
    gaia.refit$coef[4:9], rep(0,2), gaia.refit$coef[10:12]),
  bmean), beside=TRUE, col=c("blue", "red", "green"),
  legend.text=c("Lasso", "refit LASSO", "Bayesian Lasso"))
```


```{r}
gaia.lm0 <- lm(temperature~1, data=gaia)
gaia.lm  <- lm(temperature~band1+band2+band3+band4+band5+band6+
   band7+band8+band9+band10+band11+band12+
   band13+band14+band15+band16, data=gaia)
step(gaia.lm0, scope=list(lower=gaia.lm0, upper=gaia.lm),
   data=gaia, direction="forward", trace=FALSE)
```

```{r}
n <- dim(gaia)[1]
step(gaia.lm0, scope=list(lower=gaia.lm0, upper=gaia.lm),
   data=gaia, direction="forward",  k=log(n), trace=FALSE)
```

```{r}
require(MASS)
data(cpus)
y <- log(cpus$perf)
x <- log(cpus$mmax) 
plot(x,y)
```

```{r}
plot2d.pca<- function(Z, add.proj=FALSE, sd=2,  ...){
  
  n <- dim(Z)[1]
  plot(Z,...)
  eigen.var  <- eigen(var(Z))
  
  gamma1 <- eigen.var[[2]][,1]
  lambda1<- eigen.var[[1]][1]
  pcline1a   <- colMeans(Z) -  sd*sqrt(lambda1)* gamma1
  pcline1b   <- colMeans(Z) +  sd*sqrt(lambda1)* gamma1 #
  segments(pcline1a[1], pcline1a[2], pcline1b[1], pcline1b[2], col=2, lwd=2)
  
  if (add.proj){
    t1  <- t(gamma1)%*%(t(Z)-colMeans(Z))
    for (i in 1:n){
      segments(Z[i,1], Z[i,2], colMeans(Z)[1]+ t1[i]*gamma1[1],
               colMeans(Z)[2]+t1[i]*gamma1[2] , col=2, lty=2)
    }
  }  
}

```

```{r}
plot2d.pca(cbind(x,y), sd=3, add.proj=FALSE, xlab="age", ylab="circumference")
# for comparison: linear regression line
lm1<- lm(y~x)
#plot(x,y)
abline(lm1,col=4, lwd=2)
legend(4, 7, c("1st PC", "Regression"), lty=c(1,1), col=c(2,4), lwd=c(2,2))


plot2d.pca(cbind(x,y), sd=3, add.proj=TRUE)

plot(x,y)
abline(lm1,col=4, lwd=2)
# Projections for regression:
for (i in 1:208){
  segments(x[i], y[i], x[i], lm1$fitted[i], col=4, lty=2)
}

# Add a legend:
legend(4, 7, c("1st PC", "Regression", " ", "Projections" ), lty=c(1,1,2,2), col=c(2,4,2,4))
```


```{r}
gaia.pr <- prcomp(gaia[,5:20])
gaia.pr$x[1:4,1:4]
```

```{r}
Gaia <- cbind(gaia, gaia.pr$x)
colnames(Gaia)
```


```{r}
summary(lm(gaia$temperature~ PC1 + PC2 + PC3, data=Gaia))
summary(lm(gaia$temperature~ PC1 + PC2 + PC3 + PC4, data=Gaia))
```

