---
title: "ASML Regression R Code Part 3"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---
`

```{r}
fossil<- read.table("http://www.maths.dur.ac.uk/~dma0je/Data/fossil.dat",
   header=TRUE, sep="," ) 
dim(fossil)
attach(fossil)
plot(age, strontium.ratio)
```

```{r}
require(pspline)
fossil.spline <-  sm.spline(age,  strontium.ratio)
fossil.spline

plot(age, strontium.ratio)
lines(fossil.spline, col=2, lwd=2)
```

```{r}
require(KernSmooth)
fossil.loc <- locpoly(age, strontium.ratio, bandwidth=2)
plot(age, strontium.ratio)
lines(fossil.loc, col=2)
fossil.loc
```


```{r}
h<-c(0.5,1,2,4)
par(mfrow=c(2,2), cex.main=0.7, cex.lab=0.6, cex.axis=0.8)
for (j in 1:4){
  fit<- locpoly(age, strontium.ratio, bandwidth=h[j])
  plot(age, strontium.ratio, main=h[j])
  lines(fit, col=2)
}  
```

```{r}
require(KernSmooth)
h <- dpill(fossil$age, fossil$strontium.ratio,  truncate=FALSE)
h
fossil.h <- locpoly(age, strontium.ratio, bandwidth=h)
```

```{r}
plot(age, strontium.ratio)
lines(fossil.h$x, fossil.h$y,  col=3, lwd=3)
```

```{r}
fam.fit <- matrix(0,50,401)
h.grid <- seq(0.1,5, by=0.1)
for (j in 1:50){
  fam.fit[j,]<-locpoly(age, strontium.ratio,
     bandwidth=h.grid[j])$y
}
plot(age, strontium.ratio)
for ( j in 3:50){
  lines(fossil.h$x, fam.fit[j,], col="grey80")
}
lines(fossil.h$x, fossil.h$y, col=2, lwd=3)
legend(100, 0.70725, legend="dpill solution",
lwd=3, col=2)
```

```{r}
smooth.loc<- function(x,y,xgrid=x, h){
  N<-length(xgrid)
  smooth.est<-rep(0,N)
  for (j in 1:N){
    smooth.est[j]<- lm(y~I(x-xgrid[j]),
    weights=dnorm(x,xgrid[j],h) )$coef[1]
  }
list(x= xgrid, fit=smooth.est)
}

fossil.loc <- smooth.loc(age, strontium.ratio,
              h=h)
plot(age, strontium.ratio)
lines(age[order(age)], fossil.loc$fit[order(age)], 
    col=3, lwd=2)
# Note: the curve looks slightly different than the curve above as it is 
# evaluated at different target points
```

```{r}
foss.res <- strontium.ratio- fossil.loc$fit
boot.fit <- matrix(0,200,106)
for (j in 1:200){
  boot.res <- sample(foss.res, size=106)
  new.y    <-  fossil.loc$fit +boot.res
  # h <- dpill(age, new.y,  truncate=FALSE)
     # the line above would be used to account for uncertainty in selection of h
     # but numerically unstable
  boot.fit[j,] <-  smooth.loc(age, new.y, h=h)$fit
}    

lower<-upper<- rep(0,106)
for (i in 1:106){
  lower[i]<-quantile(boot.fit[,i],0.025)
  upper[i]<-quantile(boot.fit[,i],0.975)
}

plot(age, strontium.ratio)
for (j in 1:200){ lines(age[order(age)], boot.fit[j,][order(age)], col="grey")}
lines(age[order(age)], fossil.loc$fit[order(age)])
lines(age[order(age)], upper[order(age)], col=2, lwd=3)
lines(age[order(age)], lower[order(age)], col=2, lwd=3)

```

```{r}
ocean <- read.table(
    "http://www.maths.dur.ac.uk/~dma0je/Data/ocean.dat", 
    header=TRUE, sep=","
    )
```


```{r}
require(lattice)
cloud(Temp~Sal+O2, data=ocean)
```


```{r}

xsal<- seq(min(ocean$Sal), max(ocean$Sal), length=50)
xO2<- seq(min(ocean$O2), max(ocean$O2), length=50)

h1<- diff(range(xsal/10))
h2<- diff(range(xO2)/10)

fitocean <- matrix(0,50, 50)
for (i in 1:50){
  for (j in 1:50){
    bi <- ocean$Sal-xsal[i]
    bj <- ocean$O2-xO2[j]
    fitocean.lm <- lm(Temp~bi+bj, weights = dnorm(Sal, xsal[i],h1) * dnorm(O2, xO2[j],h2), 
                      data = ocean)
    fitocean[i,j]<-fitocean.lm[[1]][1]
  }
}

persp(xsal, xO2, fitocean, 
     xlab="Sal", ylab="O2", zlab="Temp", theta=-50)

```

```{r}
require(gam)
ocean.am <- gam(Temp~lo(Depth)+lo(Sal)+lo(O2), data=ocean)
par(mfrow=c(1,3))
plot(ocean.am)

```

```{r}
require(splines)
x <- seq(0, 1, by=0.001)
spl <- bs(x,df=10, degree=1)
plot(x, spl[,1], ylim=c(0,max(spl)), type='l', lwd=2,  
     xlab="Linear B-spline basis", ylab="")
for (j in 2:ncol(spl)){lines(x, spl[,j], lwd=2, col=j)}

```

```{r}
x <- seq(0, 1, by=0.001)
spl <- bs(x,df=10, degree=2)
plot(x, spl[,1], ylim=c(0,max(spl)), 
     type='l', lwd=2,  
     xlab="Cubic B-spline basis", ylab="")
for (j in 2:ncol(spl)){
     lines(x, spl[,j], lwd=2, col=j)}
```

```{r}
x <- seq(0, 1, by=0.001)
spl <- bs(x,df=10, degree=3)
plot(x, spl[,1], ylim=c(0,max(spl)), 
     type='l', lwd=2, 
     xlab="Cubic B-spline basis", ylab="")
for (j in 2:ncol(spl)){
     lines(x, spl[,j], lwd=2, col=j)}

```

```{r}
require(splines)
fit.s1<-
  lm(strontium.ratio~ bs(age, df=10, degree=3), data=fossil) 

plot(age, strontium.ratio, data=fossil)
lines(age[order(age)], predict(fit.s1)[order(age)], 
  lwd=2, col=2)

```


```{r}
require(smooth.spline)
fossil.Bspline <- smooth.spline(age, strontium.ratio)
plot(fossil$age, fossil$strontium.ratio)
lines(fossil.Bspline, col=2,lwd=2)
```


```{r}
require(gam)
ocean.gam.spline <-  gam(Temp~s(Depth)+s(Sal)+s(O2), data=ocean)
par(mfrow=c(1,3))
plot(ocean.gam.spline, rugplot=TRUE, se=TRUE, col=2)
```
