---
title: "ASML Regression R Code Part 4"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---

```{r}
expCov <- function(X1,X2,l=1) {
  Sigma <- matrix(rep(0, length(X1)*length(X2)), nrow=length(X1))
  for (i in 1:nrow(Sigma)) {
    for (j in 1:ncol(Sigma)) {
      Sigma[i,j] <-  exp(-0.5*(abs(X1[i]-X2[j])/l)^2)
    }
  }
  return(Sigma)
}
```


```{r}
x.star <- seq(-5,5,len=51)
sigma  <- expCov(x.star,x.star)
```


```{r}
require(MASS)
n.samples <- 3
values <- matrix(rep(0,length(x.star)*n.samples), ncol=n.samples)
for (i in 1:n.samples) {
  values[,i] <- mvrnorm(1, rep(0, length(x.star)), sigma)
}

par(mfrow=c(1,1))
plot(x.star, values[,1], ylim=c(-3,3), type="l")
lines(x.star, values[,2], )
lines(x.star, values[,3])
```


```{r}
sigma <- expCov(x.star,x.star, l=1/4)
values <- matrix(rep(0,length(x.star)*n.samples), ncol=n.samples)
for (i in 1:n.samples) {
  values[,i] <- mvrnorm(1, x.star/2, sigma)
}

par(mfrow=c(1,1))
plot(x.star, values[,1], ylim=c(-3,3), type="l")
lines(x.star, values[,2], )
lines(x.star, values[,3])
```


```{r}
f <- data.frame(x=c(-4,-3,-1,0,2),
                y=c(-2,0,1,2,-1))

plot(f, pch=16, cex=1.5, col=2)
```


```{r}
x  <- f$x
x
head(x.star)
K  <- expCov(x,x)
Ks <- expCov(x,x.star)
Kss <- expCov(x.star,x.star)
```

```{r}
mu.star <- t(Ks)%*%solve(K)%*%f$y
sig.star <- Kss - t(Ks)%*%solve(K)%*%Ks
```

```{r}
plot(f, pch=16, cex=1.5, col=2)
lines(x.star, mu.star, lwd=3, type="l")
```


```{r}
dim(sig.star)
image(sig.star)
```

```{r}
n.samples <- 50
values <- matrix(rep(0,length(x.star)*n.samples), ncol=n.samples)
for (i in 1:n.samples) {
  values[,i] <- mvrnorm(1, mu.star, sig.star)
}
plot(x.star, values[,1], ylim=c(-3,3), type="l")
for (j in 2:49){
lines(x.star, values[,j],col=j )
}

```


```{r}
n.samples <- 1000
values <- matrix(rep(0,length(x.star)*n.samples), ncol=n.samples)
for (i in 1:n.samples) {
  values[,i] <- mvrnorm(1, mu.star, sig.star)
}
lower.band<- apply(values,1,quantile, probs=0.025)
upper.band<- apply(values,1,quantile, probs=0.975)

plot(f, pch=16, ylim=c(-3,3), col=2)
lines(x.star, mu.star,  lwd=2)
lines(x.star, lower.band, col=2, lwd=2)
lines(x.star, upper.band, col=2, lwd=2)

```



```{r}
sigma.y <- 0.1

mu.tilde  <- t(Ks)%*%solve(K + sigma.y^2*diag(1, ncol(K)))%*%f$y
sig.tilde <- Kss - t(Ks)%*%solve(K + sigma.y^2*diag(1, ncol(K)))%*%Ks
```


```{r}
dim(K)
dim(Ks)
dim(Kss)
length(mu.tilde)
dim(sig.tilde)
```

```{r}
values <- matrix(rep(0,length(x.star)*n.samples), ncol=n.samples)
for (i in 1:n.samples) {
  values[,i] <- mvrnorm(1, mu.tilde, sig.tilde)
}
plot(x.star, values[,1], ylim=c(-3,3), type="l")
for (j in 2:49){
  lines(x.star, values[,j],col=j )
}
```

```{r}
n.samples <- 1000
values <- matrix(rep(0,length(x.star)*n.samples), ncol=n.samples)
for (i in 1:n.samples) {
  values[,i] <- mvrnorm(1, mu.tilde, sig.tilde)
}
lower.band<- apply(values,1,quantile, probs=0.025)
upper.band<- apply(values,1,quantile, probs=0.975)

plot(f, pch=16, ylim=c(-3,3), col=2)
lines(x.star, mu.star,  lwd=2)
lines(x.star, lower.band, col=2, lwd=2)
lines(x.star, upper.band, col=2, lwd=2)

```


```{r}
require(DiceKriging)
model1 <- km(formula = ~1, design=data.frame(x=f$x), 
            response=data.frame(y=f$y), 
            covtype="gauss")
p <- predict(model1, data.frame(x=x.star), type="SK")

plot(f$x, f$y, col="red", pch=19, ylim=c(-3,3))
lines(x.star, p$mean,lwd=2)
lines(x.star, p$upper95, col=2)
lines(x.star, p$lower95, col=2)
```


```{r}
x.star1 <- x.star + rnorm(51,0,0.1)
p1 <- predict(model1, data.frame(x=x.star1), type="SK")
plot(f$x, f$y, col="red", pch=19, ylim=c(-3,3))
lines(x.star1, p1$mean,lwd=2)
lines(x.star1, p1$upper95, col=2)
lines(x.star1, p1$lower95, col=2)

model1
```

```{r}
model2 <- 
   km(formula = ~1, 
   design=data.frame(x=f$x), 
   response=data.frame(y=f$y), 
   covtype="gauss", 
   nugget.estim=TRUE)

model2
```

```{r}
model3 <- km(formula= ~1, design=data.frame(x=f$x), response=data.frame(y=f$y), 
            covtype="exp" 
)

p3 <- predict(model3, data.frame(x=x.star), type="SK")
plot(f$x, f$y, col="red", pch=19, ylim=c(-3.2,3.2))
lines(x.star, p3$mean,lwd=2)
lines(x.star, p3$upper95, col=2)
lines(x.star, p3$lower95, col=2)
```

```{r}
model4 <- km(formula= ~1, design=data.frame(x=f$x), response=data.frame(y=f$y), 
            covtype="matern3_2", 
)
p4 <- predict(model4, data.frame(x=x.star), type="SK")
plot(f$x, f$y, col="red", pch=19, ylim=c(-3.2,3.2))
lines(x.star,p4$mean,lwd=2)
lines(x.star,p4$upper95, col=2)
lines(x.star,p4$lower95, col=2)
```

```{r}
fossil <-
 read.table("http://www.maths.dur.ac.uk/~dma0je/Data/fossil.dat",
 header=TRUE, sep=",")
dim(fossil)
attach(fossil)
plot(age, strontium.ratio)

```

```{r}
foss.model <- 
  km(formula = ~1, 
  design=data.frame(x=age), 
  response=data.frame(y=strontium.ratio), 
  covtype="gauss", 
  nugget.estim=TRUE
)

foss.model

```

```{r}
age.star<- seq(90,125, length=100)
foss.p <- predict(foss.model, data.frame(x=age.star), 
          type="SK")

```

```{r}
plot(age, strontium.ratio, ylim=c(0.7072, 0.7076))
lines(age.star, foss.p$mean, lwd=2, pch=19)
lines(age.star, foss.p$lower95, col=2)
lines(age.star, foss.p$upper95, col=2)
```

```{r}
plot(foss.model)
```


```{r}
foss.model2 <- 
  km(formula = ~x, 
  design=data.frame(x=age), 
  response=data.frame(y=strontium.ratio), 
  covtype="gauss", 
  nugget.estim=TRUE
)

foss.model2
```






